[package]
name = "signals-js"
version = "1.0.0"
authors = ["DipokalLab"]
repository = "https://github.com/DipokalLab/signals-js"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "core"
path = "core/lib.rs"

[dependencies]
js-sys = "0.3.69"
wasm-bindgen = "0.2"
